version: "3"

services:
  # debugger:
  #   image: ubuntu
  #   hostname: ubuntu
  #   command: sleep infinity
  #   cpus: 1
  #   mem_limit: 1g
  #   network_mode: host

  server1:
    image: kotlin_server
    hostname: server1
    environment:
      - PORT=3001
      - NUMBER_OF_PRIMES=${NUMBER_OF_PRIMES:-1500}
      - STREAMING_SERVER=localhost
      - STREAMING_SERVER_PORT=${STREAMING_SERVER_PORT:-3030}
      - STRING_CONCAT_SIZE=${STRING_CONCAT_SIZE:-10000}
    cpus: 4
    mem_limit: 1g
    network_mode: host

  server2:
    image: kotlin_server
    hostname: server2
    environment:
      - PORT=3002
      - NUMBER_OF_PRIMES=${NUMBER_OF_PRIMES:-1500}
      - STREAMING_SERVER=localhost
      - STREAMING_SERVER_PORT=${STREAMING_SERVER_PORT:-3030}
      - STRING_CONCAT_SIZE=${STRING_CONCAT_SIZE:-10000}
    cpus: 4
    mem_limit: 1g
    network_mode: host

  server3:
    image: kotlin_server
    hostname: server3
    environment:
      - PORT=3003
      - NUMBER_OF_PRIMES=${NUMBER_OF_PRIMES:-1500}
      - STREAMING_SERVER=localhost
      - STREAMING_SERVER_PORT=${STREAMING_SERVER_PORT:-3030}
      - STRING_CONCAT_SIZE=${STRING_CONCAT_SIZE:-10000}
    cpus: 4
    mem_limit: 1g
    network_mode: host

  server4:
    image: kotlin_server
    hostname: server4
    environment:
      - PORT=3004
      - NUMBER_OF_PRIMES=${NUMBER_OF_PRIMES:-1500}
      - STREAMING_SERVER=localhost
      - STREAMING_SERVER_PORT=${STREAMING_SERVER_PORT:-3030}
      - STRING_CONCAT_SIZE=${STRING_CONCAT_SIZE:-10000}
    cpus: 4
    mem_limit: 1g
    network_mode: host

  streaming_server:
    image: streaming-server
    hostname: streaming_server
    environment:
      - PORT=3031
      - API_CALL_DELAY_MS=${API_CALL_DELAY_MS:-5000}
      - STREAM_SIZE=${STREAM_SIZE:-1000000}
    cpus: 1
    mem_limit: 512m
    network_mode: host

  streaming_server2:
    image: streaming-server
    hostname: streaming_server
    environment:
      - PORT=3032
      - API_CALL_DELAY_MS=${API_CALL_DELAY_MS:-5000}
      - STREAM_SIZE=${STREAM_SIZE:-1000000}
    cpus: 1
    mem_limit: 512m
    network_mode: host

  nginx:
    image: nginx
    cpus: 4
    mem_limit: 1g
    ports:
      - "3000:3000"
      - "3030:3030"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - streaming_server
      - streaming_server2
    network_mode: host

  test:
    image: node:21.5.0-slim
    volumes:
      - ../nodejs/src/:/app/
    environment:
      - NUMBER_OF_PRIMES=${NUMBER_OF_PRIMES:-1500}
      - STRING_CONCAT_SIZE=${STRING_CONCAT_SIZE:-10000}
      - STREAM_SIZE=${STREAM_SIZE:-1000000}
      - TEST_TARGET_HOST=localhost
      - TEST_TARGET_PORT=3000
      - TEST_TARGET_STREAMING_HOST=localhost
      - TEST_TARGET_STREAMING_PORT=${STREAMING_SERVER_PORT:-3030}
    command: sh -c "npm install && npm test"
    working_dir: /app
    cpus: 1
    mem_limit: 512m
    depends_on:
      - nginx
    network_mode: host
